spring:
  data:
    mongodb:
      username: training
      password: training
      host: localhost
      port: 27017
      database: fitness-recommendations
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

server:
  port: 8095
  servlet:
    context-path: /api/v1/

eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}