spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9098/realms/fitness-network/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/v1/activities/**

        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/v1/recommendations/**
    config:
      enabled: false

server:
  port: 8080

eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka

spring-security:
  issuer-uri: http://localhost:9098/realms/fitness-network

